### ISSUE TITLE
登陆问题

### ISSUE THREAD

**Issue by zy0525** [ZHENFENG13/perfect-ssm#1]
点击登陆按钮，提示错误：
POST http://localhost:8180/users/cookie 404 (Not Found)
send @ jquery.min.js:4
ajax @ jquery.min.js:4
login @ login.js:13
onclick @ login.jsp:49

看url是Ajax提交post请求时没有把工程路径拼完整，请问该修改哪一块？

**Comment by ZHENFENG13** [comment]
不太确定，问题是404，可能是没部署好或者你的设置问题，不是个大问题，你检查一下
