### ISSUE TITLE
登录不上

### ISSUE THREAD

**Issue by HelloWorld521** [ZHENFENG13/perfect-ssm#5]
使用 admin/123456 登录不上，页面无反应
控制台 xhr cookie 返回数据
{resultCode: 500, message: "请认真核对账号、密码！", data: null}
data
:
null
message
:
"请认真核对账号、密码！"
resultCode
:
500

**Comment by HelloWorld521** [comment]
ok 了

**Comment by ZHENFENG13** [comment]
是不是密码错了。。。
