### ISSUE TITLE
上传图片的时候 你这个没有存 path 啊？ 

### ISSUE THREAD

**Issue by Dorothylyly** [ZHENFENG13/perfect-ssm#6]
![tim 20180621234522](https://user-images.githubusercontent.com/36158714/41730017-4691a61a-75ad-11e8-9a32-5c40834c22c9.png)
这个问题我找了好久，并没有得出结论。。。

求解答！！！

**Comment by ZHENFENG13** [comment]
1.图片上传成功了么？
2.浏览器上f12看看接口，请求body里字段有没有值。

**Comment by ZHENFENG13** [comment]
1.ImageController作为文件上传处理器，只做图片的存储以及路径的返回，不做其他操作。
2.PictureController作为图片信息处理器，负责存储图片的路径及其他信息。

所以图片上传成功不等于路径存储成功，上传成功后会把路径返回给页面，页面会有input域来存储这个值，之后**点击保存按钮**后，所有信息交给PictureController，然后再调用Service做处理。

不用想得太复杂。

**Comment by Dorothylyly** [comment]
哦，明白了........，那你为什么不用enctype multipart/form-data直接将图片和数据一起提交到一个Controller处理....我觉得这样逻辑简单些😬

**Comment by ZHENFENG13** [comment]
图片上传是公共服务

**Comment by Dorothylyly** [comment]
好的，谢谢你
