### ISSUE TITLE
关于Redis的一个问题

### ISSUE THREAD

**Issue by tujietg** [ZHENFENG13/perfect-ssm#9]
你好，我有一个关于Redis的问题。我单独测试了RedisUtil模块，配置了远程的Redis连接，但是我利用RedisUtil工具增加String的时候，无法在远程的redis查询到，但是调用RedisUtil的get方法可以获取到。这个是什么问题？

**Comment by ZHENFENG13** [comment]
database是不是没有选择对，你操作的是redis的哪个database要搞清楚

**Comment by tujietg** [comment]
好的，谢谢你。
